# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '_uiFiles/calculator2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(355, 475)
        Dialog.setMinimumSize(QtCore.QSize(355, 475))
        Dialog.setMaximumSize(QtCore.QSize(355, 475))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("_uiFiles\\../image/calculator.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("_uiFiles\\../image/delete.jpg"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        Dialog.setWindowIcon(icon)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(15, 15, 317, 130))
        self.widget.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widget.setObjectName("widget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(238, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.q_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.q_lineEdit.setMinimumSize(QtCore.QSize(0, 45))
        self.q_lineEdit.setStyleSheet("font: 20pt \"1훈핑크풍차 R\";")
        self.q_lineEdit.setText("")
        self.q_lineEdit.setFrame(False)
        self.q_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.q_lineEdit.setObjectName("q_lineEdit")
        self.gridLayout_2.addWidget(self.q_lineEdit, 0, 0, 1, 2)
        self.a_lineEdit = QtWidgets.QLineEdit(self.widget)
        self.a_lineEdit.setMinimumSize(QtCore.QSize(0, 45))
        self.a_lineEdit.setStyleSheet("font: 23pt \"1훈핑크풍차 R\";")
        self.a_lineEdit.setFrame(False)
        self.a_lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.a_lineEdit.setObjectName("a_lineEdit")
        self.gridLayout_2.addWidget(self.a_lineEdit, 1, 0, 1, 2)
        self.del_pushButton = QtWidgets.QPushButton(self.widget)
        self.del_pushButton.setMinimumSize(QtCore.QSize(73, 28))
        self.del_pushButton.setText("")
        self.del_pushButton.setObjectName("del_pushButton")
        self.gridLayout_2.addWidget(self.del_pushButton, 2, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(16, 160, 320, 302))
        self.widget1.setObjectName("widget1")
        self.gridLayout = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.num_pushButton_0 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_0.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_0.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_0.setObjectName("num_pushButton_0")
        self.gridLayout.addWidget(self.num_pushButton_0, 5, 1, 1, 1)
        self.sing_pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.sing_pushButton_2.setMinimumSize(QtCore.QSize(0, 45))
        self.sing_pushButton_2.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.sing_pushButton_2.setObjectName("sing_pushButton_2")
        self.gridLayout.addWidget(self.sing_pushButton_2, 2, 3, 1, 1)
        self.num_pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_2.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_2.setObjectName("num_pushButton_2")
        self.gridLayout.addWidget(self.num_pushButton_2, 2, 1, 1, 1)
        self.num_pushButton_9 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_9.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_9.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_9.setObjectName("num_pushButton_9")
        self.gridLayout.addWidget(self.num_pushButton_9, 4, 2, 1, 1)
        self.num_pushButton_6 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_6.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_6.setObjectName("num_pushButton_6")
        self.gridLayout.addWidget(self.num_pushButton_6, 3, 2, 1, 1)
        self.num_pushButton_5 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_5.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_5.setObjectName("num_pushButton_5")
        self.gridLayout.addWidget(self.num_pushButton_5, 3, 1, 1, 1)
        self.sing_pushButton_3 = QtWidgets.QPushButton(self.widget1)
        self.sing_pushButton_3.setMinimumSize(QtCore.QSize(0, 45))
        self.sing_pushButton_3.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.sing_pushButton_3.setObjectName("sing_pushButton_3")
        self.gridLayout.addWidget(self.sing_pushButton_3, 3, 3, 1, 1)
        self.per_pushButton = QtWidgets.QPushButton(self.widget1)
        self.per_pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.per_pushButton.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.per_pushButton.setObjectName("per_pushButton")
        self.gridLayout.addWidget(self.per_pushButton, 5, 0, 1, 1)
        self.num_pushButton_3 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_3.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_3.setObjectName("num_pushButton_3")
        self.gridLayout.addWidget(self.num_pushButton_3, 2, 2, 1, 1)
        self.sing_pushButton_4 = QtWidgets.QPushButton(self.widget1)
        self.sing_pushButton_4.setMinimumSize(QtCore.QSize(0, 45))
        self.sing_pushButton_4.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.sing_pushButton_4.setObjectName("sing_pushButton_4")
        self.gridLayout.addWidget(self.sing_pushButton_4, 4, 3, 1, 1)
        self.num_pushButton_7 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_7.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_7.setObjectName("num_pushButton_7")
        self.gridLayout.addWidget(self.num_pushButton_7, 4, 0, 1, 1)
        self.num_pushButton_8 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_8.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_8.setObjectName("num_pushButton_8")
        self.gridLayout.addWidget(self.num_pushButton_8, 4, 1, 1, 1)
        self.dot_pushButton = QtWidgets.QPushButton(self.widget1)
        self.dot_pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.dot_pushButton.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.dot_pushButton.setObjectName("dot_pushButton")
        self.gridLayout.addWidget(self.dot_pushButton, 5, 2, 1, 1)
        self.result_pushButton = QtWidgets.QPushButton(self.widget1)
        self.result_pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.result_pushButton.setStyleSheet("color: rgb(149, 73, 255);\n"
"background-color: rgb(225, 213, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.result_pushButton.setObjectName("result_pushButton")
        self.gridLayout.addWidget(self.result_pushButton, 5, 3, 1, 1)
        self.num_pushButton_1 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_1.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_1.setObjectName("num_pushButton_1")
        self.gridLayout.addWidget(self.num_pushButton_1, 2, 0, 1, 1)
        self.num_pushButton_4 = QtWidgets.QPushButton(self.widget1)
        self.num_pushButton_4.setMinimumSize(QtCore.QSize(0, 45))
        self.num_pushButton_4.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 18pt \"1훈핑크풍차 R\";")
        self.num_pushButton_4.setObjectName("num_pushButton_4")
        self.gridLayout.addWidget(self.num_pushButton_4, 3, 0, 1, 1)
        self.reset_pushButton = QtWidgets.QPushButton(self.widget1)
        self.reset_pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.reset_pushButton.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(149, 73, 255);\n"
"background-color: rgb(225, 213, 255);\n"
"")
        self.reset_pushButton.setObjectName("reset_pushButton")
        self.gridLayout.addWidget(self.reset_pushButton, 0, 0, 1, 1)
        self.p_open_pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.p_open_pushButton_2.setMinimumSize(QtCore.QSize(0, 45))
        self.p_open_pushButton_2.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.p_open_pushButton_2.setObjectName("p_open_pushButton_2")
        self.gridLayout.addWidget(self.p_open_pushButton_2, 1, 0, 1, 1)
        self.p_close_pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.p_close_pushButton_2.setMinimumSize(QtCore.QSize(0, 45))
        self.p_close_pushButton_2.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.p_close_pushButton_2.setObjectName("p_close_pushButton_2")
        self.gridLayout.addWidget(self.p_close_pushButton_2, 1, 1, 1, 1)
        self.and_pushButton = QtWidgets.QPushButton(self.widget1)
        self.and_pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.and_pushButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.and_pushButton.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("_uiFiles\\../image/and_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.and_pushButton.setIcon(icon1)
        self.and_pushButton.setObjectName("and_pushButton")
        self.gridLayout.addWidget(self.and_pushButton, 1, 2, 1, 1)
        self.p_open_pushButton = QtWidgets.QPushButton(self.widget1)
        self.p_open_pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.p_open_pushButton.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.p_open_pushButton.setObjectName("p_open_pushButton")
        self.gridLayout.addWidget(self.p_open_pushButton, 0, 1, 1, 1)
        self.p_close_pushButton = QtWidgets.QPushButton(self.widget1)
        self.p_close_pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.p_close_pushButton.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.p_close_pushButton.setObjectName("p_close_pushButton")
        self.gridLayout.addWidget(self.p_close_pushButton, 0, 2, 1, 1)
        self.sing_pushButton_1 = QtWidgets.QPushButton(self.widget1)
        self.sing_pushButton_1.setMinimumSize(QtCore.QSize(0, 45))
        self.sing_pushButton_1.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.sing_pushButton_1.setObjectName("sing_pushButton_1")
        self.gridLayout.addWidget(self.sing_pushButton_1, 0, 3, 1, 1)
        self.or_pushButton = QtWidgets.QPushButton(self.widget1)
        self.or_pushButton.setMinimumSize(QtCore.QSize(0, 45))
        self.or_pushButton.setStyleSheet("font: 18pt \"1훈핑크풍차 R\";\n"
"color: rgb(16, 144, 255);\n"
"background-color: rgb(224, 253, 255);")
        self.or_pushButton.setObjectName("or_pushButton")
        self.gridLayout.addWidget(self.or_pushButton, 1, 3, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.a_lineEdit.setText(_translate("Dialog", "0"))
        self.num_pushButton_0.setText(_translate("Dialog", "0"))
        self.sing_pushButton_2.setText(_translate("Dialog", "*"))
        self.num_pushButton_2.setText(_translate("Dialog", "2"))
        self.num_pushButton_9.setText(_translate("Dialog", "9"))
        self.num_pushButton_6.setText(_translate("Dialog", "6"))
        self.num_pushButton_5.setText(_translate("Dialog", "5"))
        self.sing_pushButton_3.setText(_translate("Dialog", "-"))
        self.per_pushButton.setText(_translate("Dialog", "%"))
        self.num_pushButton_3.setText(_translate("Dialog", "3"))
        self.sing_pushButton_4.setText(_translate("Dialog", "+"))
        self.num_pushButton_7.setText(_translate("Dialog", "7"))
        self.num_pushButton_8.setText(_translate("Dialog", "8"))
        self.dot_pushButton.setText(_translate("Dialog", "."))
        self.result_pushButton.setText(_translate("Dialog", "Result"))
        self.num_pushButton_1.setText(_translate("Dialog", "1"))
        self.num_pushButton_4.setText(_translate("Dialog", "4"))
        self.reset_pushButton.setText(_translate("Dialog", "C"))
        self.p_open_pushButton_2.setText(_translate("Dialog", "<"))
        self.p_close_pushButton_2.setText(_translate("Dialog", ">"))
        self.and_pushButton.setText(_translate("Dialog", "&"))
        self.p_open_pushButton.setText(_translate("Dialog", "("))
        self.p_close_pushButton.setText(_translate("Dialog", ")"))
        self.sing_pushButton_1.setText(_translate("Dialog", "/"))
        self.or_pushButton.setText(_translate("Dialog", "|"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
